@startuml

package java.lang {

    +interface Iterable<T> {
        +Iterator<T> iterator()
    }
}

package de.fhro.inf.prg3.a04.collections {
    +interface SimpleList<T> extends Iterable {
        +add(item: T)
        +addEmpty()
        +size(): int
        +default filter(filter: SimpleFilter<T>): SimpleList
        +default <R> map(Function<T, R> transform): SimpleList<R>
    }
    +abstract class CollectionsUtility {
        +{static}<T> sort(SimpleList<T> list, Comparator<T> cmp): SimpleList<T>
    }
}
@enduml